#!/bin/bash
if [[ $EUID -eq 0 ]]; then
    echo "$(tput setaf 1)Do not run puyo as $(tput setaf 2)root!"
    exit 1
fi
# puyo, the overly friendly pacman wrapper. for those who don't like soup. version 0.7
#
#                                                                                              ,'++++++++;.           
#                 ```                                  `:'''';,`                            :++++++'''++++++'.        
#            :;''''''''':`                          .'''''''''''''.                       ;'++';;;;;;;';;;;'+++.      
#         .'''''''''''''''';                      `''''': ;''''''''',                   .+++;;;;;;;;;+++;;;;;'++'     
#       .'''''::::::::::;'''':                   ;''';;;'' :':''''''''`                ;++;;;;;;;;;;',++;;;;;;;'+'    
#      ;''';:::::::::::::::''''                 ''';;;;;;'` +;' ''''''',              ;++;;;;;;;;;;+:`+.+;;;;;;;'+'   
#     ''';:::::::::::::::::::'''.              ''';;;;;;;': ''`.';;;;;'';            ,++;;;;;;;;;;+; .+ '';;;;;;;'+:  
#    '''::::::::::::::::::::::;''.            ''';;;;;;;;': '+ ;';;;;;;'':           ++;;;;;;;;;;+;  :+  +;;;;;;;;++  
#   ;''::::::::::::::::::::::::;''           :'';;;;;;;;;'` '' ';;;;;;;;''`         '+;;;;;;;;;;':   ;+ `.+;;;;;;;;+; 
#  .''::::::::::::::::::::::::::;''          ''';;;;;;;;;'  '' ;';;;;;;;;''         ++;;;;;;;;'+'    '+;+'++;;;;;;;++ 
#  '';:::::::::::::::::::::::::::'',        ''`';;;;;;;;'` :'' ,';;;;;;;;'',       .+';;;;;''+'''.   '++'''++';;;;;++ 
# `';':::::::::::::::::::::::::::;''        '' +';;;;;'+`  ';'  ';;;;;;;;'''       ;++++++''''''''  `++'''''':'';;;++ 
# ;' '':::::::::::::::::::::::::::''`      ,''  +''''+:   '':+. `';;;;;;;'''`      '+, '''''''''''  ''+''''''` `'++'+ 
# '' `'':::;::::::::::::::::::;:::;':      '''   `..     '':;;'  .'';;;;'+'',      ++' +''''''''''  +;+'''''';     '+ 
# ''  '''::':::;;:::::::::::;''::::''      '''`        `'':;;;':   ''''''`;''      +++`+''''''''': '';''''''';    `+' 
# ''  ';'';'::''::::::::::;'':'::::''      ''''`     ,'';:;;;;;',   `,:.  ;''      '+'+'''''''''+ ;';;;+''''';    ++  
# ''  ';;''';'':::::::;'''''  '::::''      '';'+'''''';:;;;;;;;;':        +''      ;+;'+''''''''''';;;;;''''',   ++'  
# ''  ';;;;''''''''''';;;;;' .'::::''      '';:;:;;::;;;;;;;;;;;;''`     .'''      `+';;++'''''++';;;;;;'+'''  .+++`  
# ''  ';;;;;'  ```';;;;;;;;; :'::::''      ''':;;;;;;;;;;;;;;;;;;:;''''''''';       ++;;;;''''';;;;;;;;;;;'++''+'+;   
# ;'. ;;;;;''     ';;;;;;;;; '':::;';      ,'':;;;;;;;;;;;;;;;;;;;;:;;;;;;''.       '+;;;;;;;;;;;;;;;;;;;;;;;;;;++    
# `'; ,;;;;''`    ;;;;;;;;;. ';:::''.       '';;;;;;;;;;;;;;;;;;;;;;;;;;;:''        `+';;;;;;;;;;;;;;;;;;;;;;;;'+.    
#  ''; '''';';    .;;;;;;;' ;'::::''        ''':;;;;;;;;;;;;;;;;;;;;;;;;:'''         '+;;;;;;;;;;;;;;;;;;;;;;;;+'     
#  `''':;';::'`    ';;;;;;;`';:::'';         '';:;;;;;;;;;;;;;;;;;;;;;;;;''.          ++;;;;;;;;;;;;;;;;;;;;;;'+`     
#   ;'';;::::;'    `'';;';`'':::;''          ,'';;;;;;;;;;;;;;;;;;;;;;;:'''           ,++;;;;;;;;;;;;;;;;;;;;;'+      
#    '''::::::;'.    ;'',,'':::;''`           ''';:;;;;;;;;;;;;;;;;;;;:'''`            ;+';;;;;;;;;;;;;;;;;;;;+'      
#     ''';:::::;'';:..:;'';:::;'',             ''';:;;;;;;;;;;;;;;;;::''',              '++;;;;;;;;;;;;;;;;;;;+;      
#      '''':::::::;'''';;:::;'''.               '''';;;;;;;;;;;;;;:;;''',                ;++;;;;;;;;;;;;;;;;;;';      
#       ,'''';:::::::::::;'''';                  :'''';;;;;;;;;;;;;''''`                  ,++';;;;;;;;;;;;;;;;'+      
#         ;'''''';;;;''''''''`                     ''''+'';;;;''''''';                      '++';;;;;;;;;;;;;;'+'     
#           ,;'''''''''''':                          ;''''''''''''':                         `'+++';;;;;;;;;;;;'++;`  
#               `:;;:,`                                `,'''''';.                              `'+++++''';;;;'''+++++.
#                                                                                                 `:'+++++++++++++;.  
#                                                                                                       ```````       
#                                  ;.                                     .:;;;;;;;,                                  
#                                 .;;,                                 `;;;;';;;;;;;;;,                               
#                                 ;;;;:                               ;;;;::::::::::;;;;,                             
#                                `;:,;;;                            ,;;;:::::::::::::::;;;                            
#                                ;;,,,:;;`                         :;;::::::::::::::::::;;;`                          
#                               :;:,,,,,;;;`                      ;;;:::::::::::::::::::::;;.                         
#                              ,;;,,,,:;;;;;;:                   ,;;:::::::::::::::::::::::;;`                        
#                             ,;;,,,,;:   `:;;;:                `;;:::::::::::::::::::::::::;;                        
#                            ,;;,,,,;`       `;;;.              ;;:::::::::::::::::::::::::::;;                       
#                           ,;;;:,,;`          ;;;;            `;;:::::::::::::::::::::::::::;;                       
#                          `;;``;::;   .;;;,    ;;;;           ;;:::::::::::::::::::::::::::::;;                      
#                          ;:    ;;` .;;,`.,;;`  ;:;;          ;;:::::::::::::::::::::::::::::;;                      
#                         ;;     '; ::        ,; ,::;;        `;:::::::::::::::::::::::::::::::;`                     
#                        :; :;:. ;;.,           :.;,:;.       :;:::::::::::::::::::::::::::::::;:                     
#                        ;;;``.;;;;,             `;,,;;       ;;:::::::::::::::::::::::::::::::;;                     
#                       ;;,     `;;               ;,,:;       ;;:::::::::::::::::::::::::::::::;;                     
#                       ;;       ;:.              ;,,,;,      ;;:::::::::::::::::::::::::::::::;;                     
#                      :;        ;,;              ;,,,;;      ;;:::::::::::::::::::::::::::::::;;                     
#                      ;;        ;,;`            ,:,,,;;      ;;:::::::::::::::::::::::::::::::;;                     
#                      ;;       ,:,,;            ;,,,,;;      .;:::::::::::::::::::::::::::::::;:                     
#                      ;;       ;,,,,;`        `;:,,,,;,      `;;:::::;;;;;;::::::::::::::::::;;`                     
#                      ;;      .;,,,,,;;,     ;;,,,,,,;`       ;;:::;;;;;;;;;;;';;;:::;;;;;;;;;;;`                    
#                      ;;      ;,,,,,,,,:;;;;;:,,,,,,;;        ,;::;;;;;;;;;;    .;;;;;;;;;'    ;`                    
#                      ;;`    ;:,,,,,,,,,,,,,,,,,,,,,;;         ;;::;;;;;;;;;      ;;;;;;;;:   `;                     
#                      ;;;..:;:,,,,,,,,,,,,,,,,,,,,,;;`         ,;;::;;;;;;;,     ,;;;;;;;;.   ;,                     
#                      .;:;;:,,,,,,,,,,,,,,,,,,,,,,,;;           ;;:::;;;;;:     :;:;;;;;;;  `;;                      
#                       ;;,,,,,,,,,,,,,,,,,,,,,,,,,;;             ;;;:::;;;;;;;';;:::;;;;;;';;.                       
#                       .;;,,,,,,,,,,,,,,,,,,,,,,,;;`              ;;;:::::;;;:::::::::::;;;`                         
#                        :;;,,,,,,,,,,,,,,,,,,,,:;;`                ;;;:::::::::::::::::;;;`                          
#                         :;;,,,,,,,,,,,,,,,,,:;;;                   ,;;;:::::::::::::;;;;                            
#                          .;;;:,,,,,,,,,,,:;;;;.                      :;;;;;;:::;;;;;;;`                             
#                            :;;;;;;::;;;;;;;;`                          .;;;;;;;;;;;:                                
#                              `:;;;;;;;;;:`                                 `...`                                    
#
black="$(tput setaf 0)"
red="$(tput setaf 1)"
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
blue="$(tput setaf 4)"
magenta="$(tput setaf 5)"
cyan="$(tput setaf 6)"
white="$(tput setaf 7)"
nc="$(tput sgr0)"
aur="no"
puyo="$HOME/.puyo"
function puyoexists {
	if pacman -Ss "^$1$" > /dev/null ; then
  	 echo ""
	else # if not in main repos pass to aur tester
 	 puyoexistsaur $@
	fi
}

function puyoexistsaur {
yay -Ss "$1" | grep "aur/$1 " >/dev/null
    if [ $? -eq 0 ];
	then
     aur="yes"
    else
     echo "${red}Package not found: ${green}$1${nc}"
     exit
    fi
}
function puyocmds {
    echo "${nc}You didn't specify a command."
    echo "${nc}You can${green} do the following actions:"
    echo "    ${nc}puyo ${green}in, install${nc} packagename${nc} - Installs a package. You can use both main and AUR packages."
    echo "    ${nc}puyo ${green}remove, rm${nc} packagename${nc} - Removes a package."
    echo "    ${nc}puyo ${green}dup, upgrade, up, update${nc} - Updates your system."
    echo "    ${nc}puyo ${green}package, pkg${nc} - Installs a package from a pkg.tar.xz file."
    echo "    ${nc}puyo ${green}install-aur, inaur${nc} - Installs a package from the AUR. Use this if install doesn't work for an AUR package."
	echo "    ${nc}puyo ${green}install-puylet, inpuylet${nc} - Installs a puylet."
	echo "    ${nc}puyo ${green}remove-puylet, rmpuylet${nc} - Removes a puylet."
}
function puyocheck {
    if [ -z "$2" ]
    then
        echo "${red}Error: no ${green}package name specified..${nc}"
        exit 1
    fi
}
function puyopkg {
 for pack in $@
 do
  puyoexists $pack
 done
}
function puyopkgaur {
 for pack in $@
 do
  puyoexistsaur $pack
 done
}
function puyoinpkg {
        if test -f "$1" > /dev/null ; then
         echo "Installing ${green}$1."
        else
         echo "File not found: ${green}$1${nc}"
         exit
        fi
}
function puyoask {
 read -p "${nc}Do you want to continue? ${green}[Y/n]${nc} " choice
 case "$choice" in
    y|Y )
    ;;
    n|N )
	echo "${nc}"
    exit
    ;;
    * )
    ;;
 esac
}
function fetch {
		{
		mkdir -p "$puyo/pkgs/"
		} &> /dev/null
		source $2
		if [ -z "$file" ]; then
			echo "You seem to be installing from an invalid puylet."
		fi
		wget -P ~/.puyo/pkgs/ "$file"
}
function puylet {

case "$1" in
	install)
		fetch $@
		{
		finder=$(find "$puyo/pkgs/" | grep "$2")
		lengths=$(find "$puyo/pkgs/" | grep -c "$2")
		source $2
		} &> /dev/null
		if (( lengths == 1 )); then
			lengths=lengths
		else
			echo "We didn't find your package."
		exit 1
		fi
		{
		mkdir -p "$puyo/temp/"
		cp "$finder" "$puyo/temp/"
		ls "$puyo/temp/"
		filename="$name.tar.gz"
		tar -xvf "$puyo/temp/$filename" -C "$puyo/temp/"
		rm "$puyo/temp/$filename"
		mkdir -p "$puyo/installed/"
		mkdir -p "$dir"
		mv "$puyo/temp/$name" "$puyo/installed/"
		} &> /dev/null
		sudo mv "$puyo/temp/"* "$dir"
	;;
	uninstall)
		{
		lengths=$(find "$puyo/installed/" | grep -c "$2")
		} &> /dev/null
		if ((lengths == 1 )); then
			lengths=lengths
		else
			echo "$2 is not installed!"
			exit 1
		fi
		{
		name="$2"
		source "$puyo/installed/$name"
		for file in $files
		do
			sudo rm $file
		done
		rm "$puyo/installed/$name"
		} &> /dev/null
	;;
esac

}
case "$1" in
    in|install)
        puyocheck "$@" #check if there's a package
	    puyopkg "${@:2}" # go through all these packages and see if they're in the repos
        echo "${nc}Installing ${green}${@:2}..."
        puyoask
		if [ "$aur" = "no" ]
		then
        	sudo pacman -S --noconfirm "${@:2}" >/dev/null
		else
			yay -S --noconfirm "${@:2}"
		fi
        ;;
    remove|rm)
        echo "${nc}Removing ${green}${@:2}..."
    	puyoask
        sudo pacman -Rns --noconfirm "${@:2}"
        ;;
    dup|upgrade|up|update)
        echo "${nc}Updating your system. ${green}This can take a while."
        puyoask
        sudo pacman -Syu --noconfirm >/dev/null
        ;;
    package|pkg)
		puyoinpkg "${@:2}"
        puyoask
	sudo pacman -U "${@:2}" --noconfirm >/dev/null
        ;;
	install-aur|inaur) 
		puyocheck "$@"
		puyopkgaur "${@:2}"
		puyoask
		yay -S --noconfirm "${@:2}"
	;;
    install-puylet|inpuylet)
	puyocheck "$@"
	echo "${nc}Installing ${green}${@:2}..."
	puylet install "$2"
    	;;
    remove-puylet|rmpuylet)
	puyocheck "$@"
	echo "${nc}Removing ${green}${@:2}..."
	puylet uninstall "$2"
	;;
	autoremove)
	sudo pacman -Rns $(pacman -Qtdq)
	;;
    *) puyocmds;;
esac
case "$1" in
    in|install) echo "${green}${@:2}${nc} has been installed.";;
    remove|rm) echo "${green}${@:2}${nc} has been removed.";;
    dup) echo "${nc}Your system has been updated.";;
    *) ;;
esac
echo "${nc}"
